var ManiaAlbum = {
  1 : "I Like Me Better",
  2 : "Silence ft. Khalid",
  3 : "Alone (Spotify extended version)",
  4 : "",
  5 : AlbumName[5],
  6 : "Spotlight",
  7 : "Walk it Talk it",
  8 : "Friends Are Family",
  9 : AlbumName[2],
  10 : "Better When I'm Dancin",
  11 : "Ode to Sleep",
  12 : "Shine Your Way",
  13 : "Fake You Out",
  14 : "Uma Therman",
  15 : "Danger",
  16 : "Rockstar",
  17 : "Thunder",
  18 : "Faded",
  19 : "6/10",
  20 : "Freaky Friday",
  21 : "Pompeii",
  22 : "Jackie Chan",
  23 : "Guns For Hands",
  24 : "Fireflies",
  25 : "Ballin'",
  26 : "Live it Up",
  27 : "Geronimo",
  28 : "I Like it",
  29 : "Classic",
  30 : "Verge",
  31 : "One Foot",
  32 : "Everyday",
  33 : "Bishops Knife Trick",
  34 : "Coming Home",
  35 : "Blood Sweat and Tears",
  36 : "I Need U",
  37 : "Save Me"
}
